import { IsNotEmpty, IsString } from "class-validator";

export class VerifyPaymentDto {
  /** Razorpay Order ID returned from order creation */
  @IsString()
  @IsNotEmpty()
  razorpayOrderId: string;

  /** Razorpay Payment ID generated by Razorpay Checkout */
  @IsString()
  @IsNotEmpty()
  razorpayPaymentId: string;

  /** Cryptographic HMAC SHA-256 signature generated by Razorpay */
  @IsString()
  @IsNotEmpty()
  razorpaySignature: string;
}
